### ISSUE TITLE
Quick Issue with django-oscar 1.1.1

### ISSUE THREAD

**Issue by ppandy** [nazariyg/Solr-5-for-django-haystack#1]
Amazing help, really got me out of a jam in a last-minute project. Just had one thing to tweek, django-oscar generated edge_ngram field types, which for whatever reason weren't loaded in Solr Filters. I think those have been deprecated? 

But in a hurry I swapped that out for "text_en", which seems to do the trick.

``` xml
{% if field.type == 'edge_ngram' %}
    <field name="{{ field.field_name }}" type="text_en" indexed="{{ field.indexed }}" stored="{{ field.stored }}" multiValued="{{ field.multi_valued }}" />
{% else %}
   <field name="{{ field.field_name }}" type="{{ field.type }}" indexed="{{ field.indexed }}" stored="{{ field.stored }}" multiValued="{{ field.multi_valued }}" />
{% endif %}
```

I know this isn't specific to haystack, but might help someone else in a similar jam.

Thanks!
Andy

**Comment by nazariyg** [comment]
Actually it is specific to haystack because `edge_ngram` and `ngram` are types that haystack defines in its Solr v4 template and depends on. So v5 template should include them too since haystack is likely to expect these types make use of `solr.EdgeNGramFilterFactory` and friends.

I made the additions after checking for any other types that could have been omitted. No need for that if-statement anymore. I'm relatively new to Solr and haven't touched ngrams yet, so currently have no way of testing it.

Hope the new template will work for you, write me back if not. Thanks a bunch.

**Comment by nazariyg** [comment]
Oh, and you'd probably need to rebuild your index if you'd like to check things properly.

**Comment by ppandy** [comment]
Yes, works like a charm! Thanks
